name: PyNE

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
    job-1:
        setup-container-first:
            runs-on: ubuntu-latest
            container:
                image: python:2.7.16
        call-workflow-first:
            uses: ./.github/workflows/run_tests.yml
    job-2:
        setup-container-second:
            runs-on: ubuntu-latest
            container:
                image: python:3.10.13
        call-workflow-second:
            uses: ./.github/workflows/run_tests.yml