name: PyNE

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
    job-1:
        runs-on: ubuntu-latest
        container:
            image: python:2.7.16
        steps:
            - uses: actions/checkout@v4
            - name: Display Current Python Version
                  run: python -c "import sys; print(sys.version)"
                - name: Install dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install flake8 pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - name: Lint with flake8
                  run: |
                    # stop the build if there are Python syntax errors or undefined names
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                - name: Test with pytest
                  run: |
                    pytest
    job-2:
        runs-on: ubuntu-latest
        container:
            image: python:3.10.13
        steps:
            - uses: actions/checkout@v4
            - name: Display Current Python Version
                  run: python -c "import sys; print(sys.version)"
                - name: Install dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install flake8 pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - name: Lint with flake8
                  run: |
                    # stop the build if there are Python syntax errors or undefined names
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                - name: Test with pytest
                  run: |
                    pytest